MVCCampProject/Controllers/WriterPanelMessageController.cs
using BuisnessLayer.Concrete;
using BuisnessLayer.ValidationRules;
using DataAccessLayer.EntityFreamwork;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCCampProject.Controllers
{
    public class WriterPanelMessageController : Controller
    {
        MessageManager messageManager = new MessageManager(new EfMessageDal());
        MessageValidator messageValidator = new MessageValidator();


        public ActionResult Inbox(string word)
        {
            string p = (string)Session["WriterEmail"];
            var inboxValues = messageManager.GetListInbox(p, word);
            return View(inboxValues);
        }

        public ActionResult SendBox(string word)
        {
            string p = (string)Session["WriterEmail"];
            var sendBoxValues = messageManager.GetListSendBox(p, word);
            return View(sendBoxValues);
        }

        public ActionResult GetMessageDetail(int id)
        {
            var messageValue = messageManager.GetById(id);
            return View(messageValue);
        }

        public PartialViewResult IndexPartial()
        {
            string p = (string)Session["WriterEmail"];

            var numberOfInbox = messageManager.GetListInbox(p).Count();
            ViewBag.inbox = numberOfInbox;

            var numberOfSendBox = messageManager.GetListSendBox(p).Count();
            ViewBag.sendBox = numberOfSendBox;

            return PartialView();
        }

        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult NewMessage(Message p)
        {
            ValidationResult results = messageValidator.Validate(p);
            string email = (string)Session["WriterEmail"];

            if (results.IsValid)
            {
                p.SenderMail = email;
                p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                messageManager.AddMessageBL(p);
                return RedirectToAction("SendBox");
            }

            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MVCCampProject/Views/WriterPanelMessage/GetMessageDetail.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetMessageDetail";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}



@Html.Action("IndexPartial", "WriterPanelMessage")
<div class="col-md-9">
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Mesaj Detayı</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
            </div>
        </div>
        <!-- /.card-header -->

        <div class="card-body p-0">
            <div class="mailbox-read-info">
                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                <br />
                <h6>
                    <b>Kimden:</b> @Html.DisplayFor(x => x.SenderMail) <br />
                    <b>Kime:</b>  @Html.DisplayFor(x => x.RecieverMail)
                    <span class="mailbox-read-time float-right">@DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToString("dd-MMM-yyyy")</span>
                </h6>
            </div>
            <div class="mailbox-read-message">
                <p>@Html.DisplayFor(x => x.MessageContent)</p>

            </div>
            <!-- /.mailbox-read-message -->
        </div>

        <!-- /.card-footer -->
    </div>
    <!-- /.card -->
</div>

MVCCampProject/Views/WriterPanelMessage/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}


@Html.Action("IndexPartial", "WriterPanelMessage")
<div class="col-md-9">
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Gelen Mesajlar</h3>
            <div class="card-tools">
                <div class="input-group input-group-sm">
                    @using (Html.BeginForm("Inbox", "WriterPanelMessage", FormMethod.Post))
                    {
                        <p>
                            Aranacak kelimeyi girin: @Html.TextBox("word")
                            <input type="submit" value="Ara" />
                        </p>
                    }
                </div>
            </div>
            <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                    <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                <div class="float-right">
                    1-50/200
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                    </div>
                    <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
            </div>
            <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="icheck-primary">
                                        <input type="checkbox" value="" id="check1">
                                        <label for="check1"></label>
                                    </div>
                                </td>
                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                <td class="mailbox-name"><a href="/WriterPanelMessage/GetMessageDetail/@item.MessageId">@item.SenderMail</a></td>
                                <td class="mailbox-subject">
                                    <b>@item.Subject</b> @item.MessageContent.Substring(0, 25)..
                                </td>
                                <td class="mailbox-attachment"></td>
                                <td class="mailbox-date"> @(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!-- /.table -->
            </div>
            <!-- /.mail-box-messages -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer p-0">
            <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                    <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                <div class="float-right">
                    1-50/200
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                    </div>
                    <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
            </div>
        </div>
    </div>
    <!-- /.card -->
</div>

MVCCampProject/Views/WriterPanelMessage/IndexPartial.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <a href="/WriterPanelMessage/NewMessage/" class="btn btn-primary btn-block mb-3">Yeni Mesaj</a>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Seçenekler</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <ul class="nav nav-pills flex-column">

                            <li class="nav-item active">
                                <a href="/WriterPanelMessage/Inbox/" class="nav-link">
                                    <i class="fas fa-inbox"></i> Gelen Mesajlar
                                    <span class="badge bg-primary float-right">@ViewBag.inbox</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/WriterPanelMessage/SendBox/" class="nav-link">
                                    <i class="far fa-envelope"></i> Gönderilenler
                                    <span class="badge bg-primary float-right">@ViewBag.sendBox</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-trash-alt"></i> Silinenler
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-envelope"></i> Talaklar
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Diğer</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <ul class="nav nav-pills flex-column">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle text-danger"></i>
                                    Önemliler
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle text-warning"></i> Tanıtımlar
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle text-primary"></i>
                                    Sosyal Medya
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->

MVCCampProject/Views/WriterPanelMessage/NewMessage.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}


@Html.Action("IndexPartial", "WriterPanelMessage")
<div class="col-md-9">
    @using (Html.BeginForm("NewMessage", "WriterPanelMessage", FormMethod.Post))
    {

        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="form-group">
                    @Html.TextBoxFor(x => x.RecieverMail, new { placeholder = "Hedef: ", @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RecieverMail)
                </div>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.Subject, new { placeholder = "Konu: ", @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Subject)
                </div>
                <div class="form-group">
                    <textarea name="MessageContent" id="compose-textarea" class="form-control" style="height: 300px">
                
                    </textarea>
                </div>
                <div class="form-group">
                    <div class="btn btn-default btn-file">
                        <i class="fas fa-paperclip"></i>  Dosya Ekle
                        <input type="file" name="attachment">
                    </div>
                    <p class="help-block">Max. 32MB</p>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <div class="float-right">
                    <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                </div>
                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
            </div>
            <!-- /.card-footer -->

        </div>
    }
    <!-- /.card -->

</div>

<!-- Control Sidebar -->
<!-- /.control-sidebar -->
<!-- ./wrapper -->
<!-- jQuery -->
<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
<!-- Summernote -->
<script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
<!-- Page Script -->
<script>
    $(function () {
        //Add text editor
        $('#compose-textarea').summernote()
    })</script>

MVCCampProject/Views/WriterPanelMessage/SendBox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}


@Html.Action("IndexPartial", "WriterPanelMessage")
<div class="col-md-9">
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Gönderilen Mesajlar</h3>
            <div class="card-tools">
                <div class="input-group input-group-sm">
                    @using (Html.BeginForm("SendBox", "WriterPanelMessage", FormMethod.Post))
                    {
                        <p>
                            Aranacak kelimeyi girin: @Html.TextBox("word")
                            <input type="submit" value="Ara" />
                        </p>
                    }
                </div>
            </div>
            <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                    <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                <div class="float-right">
                    1-50/200
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                    </div>
                    <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
            </div>
            <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="icheck-primary">
                                        <input type="checkbox" value="" id="check1">
                                        <label for="check1"></label>
                                    </div>
                                </td>
                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                <td class="mailbox-name"><a href="/WriterPanelMessage/GetMessageDetail/@item.MessageId">@item.RecieverMail</a></td>
                                <td class="mailbox-subject">
                                    <b>@item.Subject</b> @item.MessageContent.Substring(0, 25)..
                                </td>
                                <td class="mailbox-attachment"></td>
                                <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!-- /.table -->
            </div>
            <!-- /.mail-box-messages -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer p-0">
            <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                    <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                <div class="float-right">
                    1-50/200
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                    </div>
                    <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
            </div>
        </div>
    </div>
    <!-- /.card -->
</div>